import type { Document } from "./types"
import { generateId } from "./utils"

export const sampleDocuments: Document[] = [
  {
    id: generateId(),
    name: "Q1 Financial Report.pdf",
    type: "application/pdf",
    size: 2458000,
    subject: "Finance",
    keywords: ["quarterly", "financial", "report", "Q1"],
    description: "Financial report for Q1 2023 including revenue, expenses, and profit analysis.",
    uploadDate: new Date(2023, 3, 15).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
  {
    id: generateId(),
    name: "Marketing Strategy 2023.docx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 1245000,
    subject: "Marketing",
    keywords: ["strategy", "marketing", "plan", "2023"],
    description: "Comprehensive marketing strategy for 2023 including digital, social, and traditional channels.",
    uploadDate: new Date(2023, 1, 28).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
  {
    id: generateId(),
    name: "Employee Handbook.pdf",
    type: "application/pdf",
    size: 3560000,
    subject: "HR",
    keywords: ["handbook", "policies", "employees", "HR"],
    description: "Official employee handbook with company policies, benefits, and procedures.",
    uploadDate: new Date(2022, 11, 10).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
  {
    id: generateId(),
    name: "Product Roadmap.xlsx",
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 980000,
    subject: "Product",
    keywords: ["roadmap", "product", "development", "timeline"],
    description: "Product development roadmap for the next 18 months with milestones and features.",
    uploadDate: new Date(2023, 5, 5).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
  {
    id: generateId(),
    name: "Customer Survey Results.pptx",
    type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 4250000,
    subject: "Research",
    keywords: ["survey", "customer", "feedback", "analysis"],
    description: "Analysis and presentation of the annual customer satisfaction survey results.",
    uploadDate: new Date(2023, 4, 22).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
  {
    id: generateId(),
    name: "IT Security Protocol.pdf",
    type: "application/pdf",
    size: 1850000,
    subject: "IT",
    keywords: ["security", "protocol", "IT", "guidelines"],
    description: "Updated IT security protocols and guidelines for all employees.",
    uploadDate: new Date(2023, 2, 17).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
  {
    id: generateId(),
    name: "Sales Training Manual.pdf",
    type: "application/pdf",
    size: 5120000,
    subject: "Sales",
    keywords: ["training", "sales", "manual", "techniques"],
    description: "Comprehensive sales training manual for new and existing sales representatives.",
    uploadDate: new Date(2023, 0, 8).toISOString(),
    url: "/placeholder.svg?height=300&width=200",
  },
]
